
events {}
http {
    server {
        listen 8096;

        set $emby "http://172.17.0.1:8096";

        location ~* ^/preventRedirect/(emby/)?videos/(\d*)/(stream|original).* {
            rewrite ^/preventRedirect/(.*)$ /$1 break;
            proxy_pass $emby;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "";
            add_header Strict-Transport-Security "max-age=31536000";
            proxy_http_version 1.1;
            add_header Cache-Control no-cache;
            proxy_cache off;
        }

        location ~* /videos/(\d*)/(stream|original).* {
            proxy_cache off;
            proxy_buffering off;
            proxy_set_header Host $http_host;
            proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://embytoalist:60001;
        }

        location ~* /(socket|embywebsocket) {
            proxy_pass $emby;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Protocol $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_connect_timeout 1h;
            proxy_send_timeout 1h;
            proxy_read_timeout 1h;
            tcp_nodelay on;
        }

        location / {
            proxy_pass $emby;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            add_header X-Cache $upstream_cache_status;
            add_header Strict-Transport-Security "max-age=31536000";
            proxy_cache off;
        }
    }
}
